### ISSUE TITLE
Build 错误

### ISSUE THREAD

**Issue by guyingd** [FloatTech/NanoBot-Plugin#11]
root@crucial1:/home/NanoBot-Plugin# go build
# github.com/RomiChan/syncx
/root/go/pkg/mod/github.com/!romi!chan/syncx@v0.0.0-20221202055724-5f842c53020e/lazy.go:13:16: undefined: atomic.Uint32
/root/go/pkg/mod/github.com/!romi!chan/syncx@v0.0.0-20221202055724-5f842c53020e/lazy.go:14:16: undefined: atomic.Uint32
/root/go/pkg/mod/github.com/!romi!chan/syncx@v0.0.0-20221202055724-5f842c53020e/map.go:44:14: undefined: atomic.Pointer
note: module requires Go 1.19

**Comment by Jiang-Red** [comment]
你的golang版本需要1.19及以上但不能是1.21
