### ISSUE TITLE
[feature] PR申请，OpenAI相关功能

### ISSUE THREAD

**Issue by sunist-c** [FloatTech/NanoBot-Plugin#7]
# 使用OpenAI接口(或转发接口)的一些功能：

## 1. ChatGPT，可以选择模型

大致命令如下：
    `/ai gpt [(optional)model] [content...]`，如 `/ai gpt gpt-3.5 教莲宝rust`

## 2. Dalle绘画，可以选择大小

大致命令如下
    `/ai draw [(optional)size] [content...]`，如 `/ai draw large 一个泳装的莲宝`

## 3. 权限管理，OpenAI功能的权限管理

大致命令如下：
    `/ai mgnt add|remove [permissions...] <@user>`
    `/ai mgnt list <@user>`
    `/ai mgnt default [permissions...]`

# Preview

## 1. ChatGPT

<img width="500" alt="ChatGPT Preview" src="https://github.com/FloatTech/NanoBot-Plugin/assets/46150583/8ecde421-900b-4792-9665-cf6e9749f729">

## 2. Dalle

<img width="621" alt="Dalle Preview" src="https://github.com/FloatTech/NanoBot-Plugin/assets/46150583/165c5207-0111-45c0-a646-df9f8f35a73d">

## 3. Permission

<img width="627" alt="Permissions Preview" src="https://github.com/FloatTech/NanoBot-Plugin/assets/46150583/febe4df5-0809-4f0b-a5f5-6850f12a9eec">

**Comment by fumiama** [comment]
只要你代码符合规范，PR什么内容并不是问题。
